Map<String, String> lan = {"lan": "ar"};
Map<String, String> lanar = {
  "language": "اللغة",
  "Login": "تسجيل دخول",
  "CreateAccount": "انشاء حساب",
  "Okay": "حسنا",
  "Pleaseenteraccountinformationcorrect": "من فضلك ادخل بيانات حسابك صحيحة",
  "password": "كلمة السر",
  "phone": "الجوال",
  "E-mail": "البريد الإلكتروني",
  "IncorrectLoginInformation": "بيانات تسجيل الدخول خطاء",
  "LicenecImage": "صورة الترخيص",
  "FromImage": "من الصورة",
  "identityimage": "صورة الهوية",
  "country": "بلد",
  "city": "مدينة",
  "confirm": "تؤكد",
  "Settings": "إعدادات",
  "Personaldata": "البيانات الشخصية",
  "name": "الإسم",
  "Modification": "تعديل",
  "GeneralSettings": 'إعدادات عامة',
  "Arabic": "عربي",
  "English": "English",
  "records": "السجلات",
  "Aboutapp": "عن التطبيق",
  "UsagePolicy": "سياسة الإستخدام",
  "Settings": "إعدادات",
  "Tripcompleted": "تم إكمال الرحلة",
  "Servicecosts": "تكاليف الخدمة",
  "cards": "البطاقات",
  "signout": "تسجيل الخروج",
  "Acceptance": "قبول",
  "reject": "رفض",
  "statement": "الإبيان",
  "cardnumber": "رقم البطاقة",
  "Convertername": "اسم المحول",
  "Bankname": "اسم البنك",
  "amalgam": "المبلغ",
  "Notes": "ملاحضات",
  "addbank": "إضافة بنك",
  "Rial": "ريال",
  "addinvoice": "إضافة فاتوره",
  "Productsselection": "اختيار المنتجات",
  "Email": "الإيميل",
  "Helpusfindoutwhatyouoffer": "ساعدنا في معرفة ماذا تقدم",
  "Choosetrucks": "اختر الشاحنات",
  "Areyousuretochoosethetruck": "هل انت متأكد من اختيار الشاحنة",
  "Finished": "منتهي",
  "Ongoingrequests": "طلبات جارية",
  "anerroroccurred": "حدث خطاء",
  "closed": 'مغلق',
  "Activatethesitenow": 'تفعيل الموقع الأن',
  "open": 'مفتوح',
  "Sitewarningmessage":
      'يساعد تفعيل الموقع الوصول لنتائج افضل للطلبيات القريبة مما يسهل عليك الربح واستقبال الطلبات بناء على الأقرب ',
};
Map<String, String> lanen = {
  "language": "language",
  "Login": "Login",
  "CreateAccount": "Create an account",
  "Okay": "Okay",
  "Pleaseenteraccountinformationcorrect": "Please enter your account information is correct",
  "password": "password",
  "phone": "mobile",
  "E-mail": "e-mail",
  "IncorrectLoginInformation": "Wrong login data",
  "LicenecImage": "License Image",
  "FromImage": "From Image",
  "identityimage": "identity image",
  "country": "country",
  "city": "city",
  "confirm": "confirm",
  "Settings": "Settings",
  "Personaldata": "Personal Data",
  "name": "the name",
  "Modification": "Modification",
  "GeneralSettings": 'General Settings',
  "Arabic": "Arabic",
  "English": "English",
  "records": "records",
  "Aboutapp": "About the application",
  "UsagePolicy": "Usage Policy",
  "Settings": "Settings",
  "Tripcompleted": "Trip completed",
  "Servicecosts": "Service Costs",
  "cards": "cards",
  "signout": "sign out",
  "Acceptance": "Acceptance",
  "reject": "reject",
  "statement": "statement",
  "cardnumber": "card number",
  "Convertername": "Converter Name",
  "Bankname": "Bank Name",
  "amalgam": "amount",
  "Notes": "Notes",
  "addbank": "add bank",
  "Rial": "Real",
  "addinvoice": "add invoice",
  "Productsselection": "Productsselection",
  "Email": "e-mail",
  "Helpusfindoutwhatyouoffer": "Help us find out what you're offering",
  "Choosetrucks": "Choose Trucks",
  "Areyousuretochoosethetruck": "Are you sure to choose the truck",
  "Finished": "finished",
  "Ongoingrequests": "Ongoing Requests",
  "anerroroccurred": "an error occurred",
  "closed": 'closed',
  "Activatethesitenow": 'Activate the site now',
  "open": 'open',
  "Sitewarningmessage":
      'Activating the site helps to reach better results for the nearby orders, which makes it easier for you to profit and receive orders based on the closest',
};
